---
title: "Hw5"
output: github_document
---

```{r}
library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
##Problem 1
##Importing data
```{r}
homicide <- 
  read_csv("data/homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(city_state = str_c(city, state, sep = ", "),
         resolution = case_when(
           disposition == "Closed without arrest" ~ "unsolved",
           disposition == "Open/No arrest" ~ "unsolved",
           disposition == "Closed by arrest" ~ "solved")) %>% 
  relocate(city_state) %>% 
  filter(city_state != "Tulsa, AL")

homicide %>% 
  group_by(city_state, resolution) %>% 
  summarize(n = n()) %>% 
  pivot_wider(
    names_from = resolution,
    values_from = n) %>% 
  mutate(total = solved + unsolved)

```
##For Baltimore

```{r}
baltimore_df <- homicide %>% 
  filter(city_state == "Baltimore, MD")

baltimore_summary <- 
  homicide %>% 
  filter(city_state == "Baltimore, MD") %>%  
  summarize(unsolved = sum(resolution == "unsolved"), n = n())

baltimore_test <- prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n))
baltimore_test %>% broom::tidy()


```
##Function

```{r}
prop_test_function = function(x) {
   
city_summary <- 
  homicide %>% 
  filter(city_state == x) %>%  
  group_by(resolution) %>% 
  summarize(n = n()) %>% 
  pivot_wider(
    names_from = resolution,
    values_from = n) %>% 
  mutate(total = solved + unsolved)
  
city_test <- 
  prop.test(x = city_summary %>% pull(unsolved),
  n = city_summary %>% pull(total))

return(city_test)
}

prop_test_function("Baltimore, MD")
```

##Iteration and ploting
```{r}
results_df <- homicide %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(city_state, prop_test_function),
    tidy_results = map(test_results, broom::tidy)) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, conf.low, conf.high)
  
results_df %>% 
mutate(city_state = fct_reorder(city_state, estimate)) %>% 
ggplot(aes(x = city_state, y = estimate)) +
  geom_point()+
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust = 1, size = 5)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))
```

##Problem 2

```{r}
list_df <- 
  tibble(list.files("data_2", full.names = TRUE)) %>% 
  setNames("file_name") %>% 
  mutate(data = map(file_name, read_csv)) %>% 
  unnest(data) %>% 
  mutate(file_name = str_replace_all(file_name, "data_2/", ""), 
         control_arm = if_else(str_detect(file_name,"con"), "control", "case"),
         id = readr::parse_number(file_name)) %>% 
  pivot_longer(
    week_1:week_8, names_to = "week", names_prefix = "week_", values_to = "observation")

list_df %>% 
  ggplot(aes(x = week, y = observation, group=file_name, color = control_arm)) +
  geom_line(alpha = 0.7)
```
Case group on average have higher values of observations than the control group, and are trending positively through out 8 weeks, while control groups are on average showing no obvious trend. 

##Problme 3
```{r}

set.seed(10)

iris_with_missing <-  iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```

```{r}
replace_na(iris_with_missing$sepal_length, mean(iris_with_missing$sepal_length, na.rm = TRUE))
```

Function
```{r}
fill_in_missing = function(vector){
  
  if(is.numeric(vector)){
    vector %>% 
      replace_na(mean(vector, na.rm = TRUE)) %>% 
      round(digit = 3)
    
  }
  
  else if(is.character(vector)){
    vector %>% 
      replace_na("virginica")
  }
}

iris_no_missing <- 
  iris_with_missing %>% 
  map_dfc(fill_in_missing)

```


